"""Tree-ring width detrending pipeline.

Provides parsing of Tucson-format .rwl files, biological detrending via
negative exponential growth models, and Ring Width Index (RWI) calculation.
"""

from treering.export import export_csv
from treering.model import fit_growth_curve, negative_exponential
from treering.parser import parse_rwl
from treering.pipeline import process_rwl
from treering.rwi import calculate_rwi
from treering.solar_lag import (
    DataValidationError,
    LagAnalysisError,
    OptimalLagResult,
    SolarLagAnalysisResult,
    TemporalContinuityError,
    apply_centered_smoothing,
    build_final_aligned_dataframe,
    calculate_lag_correlations,
    export_results,
    load_rwi_data,
    load_sunspot_data,
    merge_datasets,
    run_solar_lag_analysis,
    select_optimal_lag,
    standardize_series,
    validate_years,
)
from treering.spei import (
    GridCellMetadata,
    SPEIAggregationError,
    SPEICoordinateError,
    SPEIError,
    SPEIExportError,
    SPEIExtractionResult,
    SPEIFileError,
    SPEITimeError,
    SPEIVariableError,
    TimeCoverageMetadata,
    aggregate_annual_spei,
    check_downstream_compatibility,
    export_annual_spei_csv,
    export_provenance_json,
    extract_annual_spei,
    extract_point_series,
    inspect_dataset,
    load_netcdf,
    resolve_spei_variable,
    to_annual_dataframe,
    validate_coordinates,
    validate_time_axis,
)

from treering.forecast import (
    CrossValidationMetrics,
    DroughtFeatureEngineer,
    DroughtForecaster,
    FeatureEngineeringError,
    ForecastError,
    ForecastYearResult,
    ModelTrainingError,
    ProjectionError,
    SolarCyclePhaseCalculator,
    run_drought_forecasting_pipeline,
)
from treering.holdout import (
    classify_spei_calibrated_3class,
    classify_spei_strict_3class,
    evaluate_geographic_holdout,
    train_and_save_gondar_model,
)

__all__ = [
    "parse_rwl",
    "negative_exponential",
    "fit_growth_curve",
    "calculate_rwi",
    "process_rwl",
    "export_csv",
    "load_rwi_data",
    "load_sunspot_data",
    "validate_years",
    "merge_datasets",
    "apply_centered_smoothing",
    "standardize_series",
    "calculate_lag_correlations",
    "select_optimal_lag",
    "build_final_aligned_dataframe",
    "run_solar_lag_analysis",
    "export_results",
    "DataValidationError",
    "TemporalContinuityError",
    "LagAnalysisError",
    "OptimalLagResult",
    "SolarLagAnalysisResult",
    "SPEIError",
    "SPEIFileError",
    "SPEIVariableError",
    "SPEICoordinateError",
    "SPEITimeError",
    "SPEIAggregationError",
    "SPEIExportError",
    "GridCellMetadata",
    "TimeCoverageMetadata",
    "SPEIExtractionResult",
    "load_netcdf",
    "inspect_dataset",
    "resolve_spei_variable",
    "validate_coordinates",
    "extract_point_series",
    "validate_time_axis",
    "aggregate_annual_spei",
    "to_annual_dataframe",
    "export_annual_spei_csv",
    "export_provenance_json",
    "check_downstream_compatibility",
    "extract_annual_spei",
    "ForecastError",
    "FeatureEngineeringError",
    "ModelTrainingError",
    "ProjectionError",
    "CrossValidationMetrics",
    "ForecastYearResult",
    "SolarCyclePhaseCalculator",
    "DroughtFeatureEngineer",
    "DroughtForecaster",
    "run_drought_forecasting_pipeline",
    "classify_spei_strict_3class",
    "classify_spei_calibrated_3class",
    "train_and_save_gondar_model",
    "evaluate_geographic_holdout",
]

